name: zwave
version: 0.11.0
author: Dan Rubel <danrubel@google.com>
description: >
  A Dart Library for interacting with Z-Wave devices on Linux.
homepage: https://github.com/danrubel/zwave.dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  logging: ^1.0.1
  path: ^1.8.0
dev_dependencies:
  grinder: ^0.9.0
  pedantic: 1.11.1
  test: ^1.17.9
