#!/bin/sh
#
# Typically, this script is run by calling
#
#    pub global run zwave:build_native
#
# See README for setup instructions

# exit on error
set -e

cd $(dirname $0)
echo building zwave in `pwd`

####################################################################
# Build rpi_zw_port native library

g++ -fPIC -c zwave_ext.cc
# use --no-undefined to check for missing libraries
gcc -shared -lpthread -Wl,-soname,libzwave_ext.so -o libzwave_ext.so zwave_ext.o

# echo "exported symbols"
# nm -g libzwave_ext.so | grep ' T '

echo "gcc build complete"
